In [4]:
pip install pandas

Collecting pandas
  Downloading pandas-2.3.0-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in d:\python\venv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\python\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in d:\python\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.0-cp312-cp312-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/11.0 MB 7.6 MB/s eta 0:00:02
   ------------ --------------------------- 3.4/11.0 MB 8.8 MB/s eta 0:00:01
   ------------------- -------------------- 5.2/11.0 MB 8.8 MB/s eta 0:00:01
   -------------------------- ------------- 7.3/11.0 MB 8.9 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/11.0 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 8.7 MB/s eta 0:00:00
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.3.0 pytz-2025.2 tzdata-2025.2
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd

df = pd.read_csv("movies.csv")
df.head(6)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English

In [11]:
df.imdb_rating.min(),df.imdb_rating.max(),df.imdb_rating.mean()

(np.float64(1.9), np.float64(9.3), np.float64(7.919444444444445))

In [14]:
df.columns

Index(['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget',
       'revenue', 'unit', 'currency', 'language'],
      dtype='object')

In [16]:
df.industry.unique()

array(['Bollywood', 'Hollywood'], dtype=object)

In [18]:
df.language.unique()

array(['Bengali', 'English', 'Hindi', 'Kannada', 'Telugu'], dtype=object)

In [20]:
df.industry.value_counts()

industry
Hollywood    20
Bollywood    17
Name: count, dtype: int64

In [21]:
df.language.value_counts()

language
English    20
Hindi      12
Telugu      3
Bengali     1
Kannada     1
Name: count, dtype: int64

In [22]:
df_new =df[["title","imdb_rating","industry"]]
df_new

                                          title  imdb_rating   industry
0                               Pather Panchali          8.3  Bollywood
1   Doctor Strange in the Multiverse of Madness          7.0  Hollywood
2                         Thor: The Dark World           6.8  Hollywood
3                               Thor: Ragnarok           7.9  Hollywood
4                       Thor: Love and Thunder           6.8  Hollywood
5                      The Shawshank Redemption          9.3  Hollywood
6                                  Interstellar          8.6  Hollywood
7                      The Pursuit of Happyness          8.0  Hollywood
8                                     Gladiator          8.5  Hollywood
9                                       Titanic          7.9  Hollywood
10                        It's a Wonderful Life          8.6  Hollywood
11                                       Avatar          7.8  Hollywood
12                                The Godfather          9.2  Hollywood
13                              The Dark Knight          9.0  Hollywood
14                             Schindler's List          9.0  Hollywood
15                                Jurassic Park          8.2  Hollywood
16                                     Parasite          8.5  Hollywood
17                            Avengers: Endgame          8.4  Hollywood
18                       Avengers: Infinity War          8.4  Hollywood
19           Captain America: The First Avenger          6.9  Hollywood
20          Captain America: The Winter Soldier          7.8  Hollywood
21                  Dilwale Dulhania Le Jayenge          8.0  Bollywood
22                                     3 Idiots          8.4  Bollywood
23                     Kabhi Khushi Kabhie Gham          7.4  Bollywood
24                             Bajirao Mastani           7.2  Bollywood
25                             Taare Zameen Par          8.3  Bollywood
26                          Munna Bhai M.B.B.S.          8.1  Bollywood
27                                           PK          8.1  Bollywood
28                                        Sanju          NaN  Bollywood
29                            The Kashmir Files          8.3  Bollywood
30                            Bajrangi Bhaijaan          8.1  Bollywood
31                                       Race 3          1.9  Bollywood
32                                    Shershaah          8.4  Bollywood
33                             K.G.F: Chapter 2          8.4  Bollywood
34                    Pushpa: The Rise - Part 1          7.6  Bollywood
35                                          RRR          8.0  Bollywood
36                     Baahubali: The Beginning          8.0  Bollywood

In [ ]:
df[(df.release_year>=2000) & (df.release_year<=2017)]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.0,701.8,Millions,USD,English
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.0,1006.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.7,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.0,714.4,Millions,USD,English
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.4,3.5,Billions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.0,8540.0,Millions,INR,Hindi
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.0,11690.0,Millions,INR,Hindi
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

:

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("movies.csv")
df.head(5)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English